### ISSUE TITLE
Moteur de recherche

### ISSUE THREAD

**Issue by sardinecan** [bibstan/ProjetDurival#18]
# Mise en place d'un moteur de recherche basé sur simpleXML et php

## Prototypage 
* [x] OK
### Possibilités
- recherche plein texte
- recherche plein texte en tenant compte d'une date et/ou d'un thème (@ana)
- extraction thématique
- extraction thématique restreinte (date)

### Validation  @enbmn 
Remarques avant optimisation du code

## TODO list

* [ ] récupération des dates dans `dateline/date/@when | dateline/date/@from`
* [x] echappement de l'apostrophe dans les requêtes.
* [x] intégration des '@ana' dans la recherche avancée. 
* [ ] /!\ /!\ /!\ remplacer dans le texte ’ par '.

**Comment by sardinecan** [comment]
@enbmn Je viens de terminer le prototype. Avant d'optimiser le code, je te laisse tester et me faire remonter tes remarques, on peut par exemple descendre au mois pour la date... à voir si c'est pertinent. les possibilités sont listées ci-dessus.

**Comment by sardinecan** [comment]
@enbmn Bonjour Éric, Je ne sais pas si nous aurons l'occasion d'en discuter avant ton départ en congés, mais pourrais-tu faire un push de l'édition TEI ? J'ai quelques améliorations que je souhaiterai apporter, par un fork du projet pour vous les soumettre à la rentrée (je l'espère) (quelques points d'encodage, test d'un autre framwork css, intégration du moteur de recherche, etc.)

Merci et à bientôt.
Josselin
