### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sardinecan** [bibstan/ProjetDurival#3]
### @sardinecan
- [x] voir alternative au switch et position @sardinecan 
- [x] traitement et chargement index pers @sardinecan 
- [x] Finir la modernisation @sardinecan
- [ ] Relecture suite modernisation + finir normalisation @sardinecan
- [x] Récupération des nouveaux facsimilés pour 1766 @enbmn @sardinecan 
  ici :
  https://drive.google.com/drive/folders/0B6NelPj0AGSDUHJMQkdKZnNOLTg
- [x] Récupération de la page index pour intégration dans xsl @enbmn @sardinecan (idem)
- [x] Retravailler le footer @sardinecan
- [x] Intégration des données de l'index des personnes @sardinecan
- [x] rassembler données @enbmn (en cours)
- [x] relecture avant intégration @enbmn
- [X] Changement de serveur @sardinecan
- [X] Modification des options d'affichage @sardinecan
### @enbmn
- [x] tri index non renseigné @enbmn
- [x] Récupération de l'index des personnes @enbmn 
- [x] voir autres pages restantes
  - [x] à propos 
    - [x] données @enbmn (header.xml en cours)
    - [x] xsl @sardinecan 
  - [x] bibliographie 
    - [x] données @enbmn
    - [x] xsl @sardinecan 
  - [x] galerie 
    - [x] données @enbmn
    - [x] xsl @sardinecan 
- [x] intégration notes dans placeList @sardinecan (suite des corrs direct dans tei)
- [x] sélection illustration et traitement (légendes, dates, thumbs...) @enbmn (en cours)
- [x]  sélection illustration et traitement (légendes, dates, thumbs...) @enbmn pour galerie avec typage
- [x] Affichage des images à reprendre (carré=>rond + problème avec d'accueil sur petit écran)
  **les vignettes sont nommées T/nomffichier/.png ici c'est donc un pb nommage.**
## Avant publication
- [ ] Relecture complète
- [ ] Terminer export LaTeX
- [ ] Finaliser le schéma
- [x] Nettoyer XSL 
- [ ] restreindre la XSL
- [ ] Nettoyer système de fichiers
## Améliorations possibles
- [ ] Migration placeName > geogName pour certaines entrées de l'index des lieux (le Rhône, la Lorraine etc.). @sardinecan
- [ ] Documentation du code @enbmn  @sardinecan 
- ~~pages cartes mauvais tab-menu~~
- ~~le switch lb cause des bugs sur tablettes (on va devoir le virer en effet)~~
- ~~bug sur les vignettes de mars à fin d'années dans l'entrée calendaire~~
